version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: realestate-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: propertydb
